customhost = "student.cr6sym2cmtkr.us-east-1.rds.amazonaws.com"
customuser = "gpaj"
custompass = "gpaj3344"
customdb = "student"
custombucket = "addkiitstudent"
customregion = "us-east-2"
customtable = "student"